services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DOCKER_GROUP_GID=999
    ports:
      - 8080:8080
    restart: always
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: "host"
